cache openfst build artifacts

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -44,6 +44,7 @@ jobs:
       cache:
         directories:
           - $HOME/AppData/Local/Temp/chocolatey
+          - travis/openfst
       before_cache:
         - rm $HOME/AppData/Local/Temp/chocolatey/*.log
       install:
@@ -55,14 +56,24 @@ jobs:
       script:
         - |
           # Build OpenFST in travis/openfst
-          set -eo pipefail
+          set -xeo pipefail
           export OPENFST_DIR="${TRAVIS_BUILD_DIR}/travis/openfst"
           mkdir -p "$OPENFST_DIR"
           cd "$OPENFST_DIR"
-          git clone -b winport --single-branch https://github.com/kkm000/openfst .
-          curl https://patch-diff.githubusercontent.com/raw/kkm000/openfst/pull/22.patch | git apply -v
-          cmake -S . -B build64 -G "Visual Studio 15 2017 Win64" "-DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/conan_paths.cmake" -DHAVE_FAR=ON -DHAVE_NGRAM=ON -DHAVE_LOOKAHEAD=ON
-          travis_wait 30 sh -c "cmake --build build64 | tail -n100"
+          if [ -f .valid-cache ]; then
+            echo "Reusing cached openfst build artifacts: " $(cat .valid-cache)
+          else
+            if [ -d .git ]; then
+              echo "Deleting cached build artifacts from failed build"
+              rm -rf *
+            fi
+            git clone -b winport --single-branch https://github.com/kkm000/openfst .
+            curl https://patch-diff.githubusercontent.com/raw/kkm000/openfst/pull/22.patch | git apply -v
+            cmake -S . -B build64 -G "Visual Studio 15 2017 Win64" "-DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/conan_paths.cmake" -DHAVE_FAR=ON -DHAVE_NGRAM=ON -DHAVE_LOOKAHEAD=ON
+            travis_wait 30 sh -c "cmake --build build64 | tail -n100"
+            git describe --always > .valid-cache
+            echo "OpenFST build successful: " $(cat .valid-cache)
+          fi
         - |
           # Build Kaldi in travis/kaldi
           set -xeo pipefail
@@ -89,7 +100,7 @@ jobs:
           ./generate_solution.pl --vsver vs2017 --enable-openblas
           ./get_version.pl
           SLN_PATH_WIN=$(win_path $(find "$KALDI_DIR" -type f -name '*.sln'))
-          msbuild "$SLN_PATH_WIN" /p:Configuration=Release|x64
+          msbuild "$SLN_PATH_WIN" "/p:Configuration=Release|x64"
           
         # - export VERSION="$(git describe --tags --always)"
         # - cd "${TRAVIS_BUILD_DIR}/python"
