debug why cache is so huge (2.2GB)
Suspect that bringing the size of the cache down would allow faster startup.
Currently Kaldi build starts at T+10min despite OpenFST  being already built
and gets killed at T+50min.

https://serverfault.com/a/367269

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -64,6 +64,22 @@ jobs:
           cd "$OPENFST_DIR"
           if [ -f .valid-cache ]; then
             echo "Reusing cached OpenFST build artifacts: " $(cat .valid-cache)
+            file_size_by_ext() {
+              declare -A ary
+
+              while IFS=$'\t' read name size; do 
+                ext=${name##*.}
+                ((ary[$ext] += size))
+              done < <(find $1 -type f  -printf "%f\t%s\n")
+
+              for key in "${!ary[@]}"; do 
+                printf "%s\t%s\n" "$key" "${ary[$key]}"
+              done
+            }
+            echo "file_size_by_ext $(pwd)"
+            file_size_by_ext .
+            echo "file_size_by_ext $(pwd)/build64"
+            file_size_by_ext build64
           else
             if [ -d .git ]; then
               echo "Deleting cached build artifacts from failed OpenFST build"
@@ -77,45 +93,45 @@ jobs:
             echo "OpenFST build successful: " $(cat .valid-cache)
           fi
         - |
-          # Build Kaldi in travis/kaldi
-          set -xeo pipefail
-          export KALDI_DIR="${TRAVIS_BUILD_DIR}/travis/kaldi"
-          mkdir -p "$KALDI_DIR"
-          cd "$KALDI_DIR"
-          if [ -f .valid-cache ]; then
-            echo "Reusing cached Kaldi build artifacts: " $(cat .valid-cache)
-          else
-            if [ -d .git ]; then
-              echo "Deleting cached build artifacts from failed Kaldi build"
-              find -mindepth 1 -delete
-            fi
-            git clone -b lookahead --single-branch https://github.com/alphacep/kaldi .
-            cd windows
-            cp variables.props.dev variables.props
-            win_path() {
-              echo $1 | sed -e 's~^/\([a-z]\)/~\1:/~i' -e 's~/~\\~g'
-            }
-            cmake_property() {
-              cat "$1" | grep "set($2 " | sed -e 's/.*"\(.*\)").*/\1/'
-            }
-            esc_sed_rhs() {
-              echo $1 | sed -e 's~\\\([0-9]\)~\\\\\1~g'
-            }
-            CONAN_OPENBLAS_ROOT=$(cmake_property "${TRAVIS_BUILD_DIR}/conan_paths.cmake" CONAN_OPENBLAS_ROOT)
-            sed -ie "s~<OPENBLASDIR>.*</OPENBLASDIR>~<OPENBLASDIR>$(esc_sed_rhs $(win_path "$CONAN_OPENBLAS_ROOT"))</OPENBLASDIR>~" variables.props
-            sed -ie "s~<OPENFST>.*</OPENFST>~<OPENFST>$(esc_sed_rhs $(win_path "$OPENFST_DIR"))</OPENFST>~" variables.props
-            sed -ie "s~<OPENFSTLIB>.*</OPENFSTLIB>~<OPENFSTLIB>$(esc_sed_rhs $(win_path "${OPENFST_DIR}/build64"))</OPENFSTLIB>~" variables.props
-            cp kaldiwin_openblas.props kaldiwin.props
-            ./generate_solution.pl --vsver vs2017 --enable-openblas
-            ./get_version.pl
-            SLN_PATH_WIN=$(win_path $(find "$KALDI_DIR" -type f -name '*.sln'))
-            cat "$SLN_PATH_WIN"
+          # # Build Kaldi in travis/kaldi
+          # set -xeo pipefail
+          # export KALDI_DIR="${TRAVIS_BUILD_DIR}/travis/kaldi"
+          # mkdir -p "$KALDI_DIR"
+          # cd "$KALDI_DIR"
+          # if [ -f .valid-cache ]; then
+          #   echo "Reusing cached Kaldi build artifacts: " $(cat .valid-cache)
+          # else
+          #   if [ -d .git ]; then
+          #     echo "Deleting cached build artifacts from failed Kaldi build"
+          #     find -mindepth 1 -delete
+          #   fi
+          #   git clone -b lookahead --single-branch https://github.com/alphacep/kaldi .
+          #   cd windows
+          #   cp variables.props.dev variables.props
+          #   win_path() {
+          #     echo $1 | sed -e 's~^/\([a-z]\)/~\1:/~i' -e 's~/~\\~g'
+          #   }
+          #   cmake_property() {
+          #     cat "$1" | grep "set($2 " | sed -e 's/.*"\(.*\)").*/\1/'
+          #   }
+          #   esc_sed_rhs() {
+          #     echo $1 | sed -e 's~\\\([0-9]\)~\\\\\1~g'
+          #   }
+          #   CONAN_OPENBLAS_ROOT=$(cmake_property "${TRAVIS_BUILD_DIR}/conan_paths.cmake" CONAN_OPENBLAS_ROOT)
+          #   sed -ie "s~<OPENBLASDIR>.*</OPENBLASDIR>~<OPENBLASDIR>$(esc_sed_rhs $(win_path "$CONAN_OPENBLAS_ROOT"))</OPENBLASDIR>~" variables.props
+          #   sed -ie "s~<OPENFST>.*</OPENFST>~<OPENFST>$(esc_sed_rhs $(win_path "$OPENFST_DIR"))</OPENFST>~" variables.props
+          #   sed -ie "s~<OPENFSTLIB>.*</OPENFSTLIB>~<OPENFSTLIB>$(esc_sed_rhs $(win_path "${OPENFST_DIR}/build64"))</OPENFSTLIB>~" variables.props
+          #   cp kaldiwin_openblas.props kaldiwin.props
+          #   ./generate_solution.pl --vsver vs2017 --enable-openblas
+          #   ./get_version.pl
+          #   SLN_PATH_WIN=$(win_path $(find "$KALDI_DIR" -type f -name '*.sln'))
+          #   cat "$SLN_PATH_WIN"
 
-            travis_wait 40 sh -c "set -eo pipefail; '/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe' '$SLN_PATH_WIN' -property:Configuration=Release -property:Platform=x64 -target:kaldi-online2 -maxcpucount | tail -n100"
+          #   travis_wait 40 sh -c "set -eo pipefail; '/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe' '$SLN_PATH_WIN' -property:Configuration=Release -property:Platform=x64 -target:kaldi-online2 -maxcpucount | tail -n100"
             
-            git describe --always > .valid-cache
-            echo "Kaldi build successful: " $(cat .valid-cache)
-          fi
+          #   git describe --always > .valid-cache
+          #   echo "Kaldi build successful: " $(cat .valid-cache)
+          # fi
           
         # - export VERSION="$(git describe --tags --always)"
         # - cd "${TRAVIS_BUILD_DIR}/python"
